DROP TABLE [dbo].[CAST_SL_RPT]
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAST_SL_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAST_SL_RPT](
	[CAST_SL_RPT_ID] [bigint] NOT NULL,
	[CAST_SL_RPT_FLAG] [bit] NOT NULL,
	[CAST_SL_WORK_ID] [varchar](10) NULL,
	[CASTSL_GI01] [varchar](3) NULL,
	[CASTSL_GI03] [varchar](3) NULL,
	[CASTSL_SB00] [varchar](10) NULL,
	[CASTSL_SL01] [varchar](10) NULL,
	[CASTSL_SL02] [varchar](10) NULL,
	[CASTSL_SL03] [varchar](1) NULL,
	[CASTSL_SL04] [varchar](1) NULL,
	[CASTSL_SL05] [varchar](1) NULL,
	[CASTSL_SL06] [varchar](1) NULL,
	[CAST_SL_WORK_ADDOPR] [varchar](20) NULL,
	[CAST_SL_WORK_ADDDATE] [datetime] NULL,
	[CAST_SL_WORK_CHGOPR] [varchar](20) NULL,
	[CAST_SL_WORK_CHGDATE] [datetime] NULL,
	[CASTSL_STUDENT_ID] [varchar](10) NULL,
	[CASTSL_KEY_IDX] [varchar](25) NULL,
	[CASTSL_STNC_ID] [varchar](10) NULL,
	[CASTSL_STNC_NON_COURSE] [varchar](10) NULL,
 CONSTRAINT [PK_SL_RPT_ID] PRIMARY KEY CLUSTERED 
(
	[CAST_SL_RPT_ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAST_SL_R__CAST___393BCAA6]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAST_SL_RPT] ADD  DEFAULT ((1)) FOR [CAST_SL_RPT_FLAG]
END
GO
