DROP TABLE [dbo].[L56_DOD_IPEDS_EF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[L56_DOD_IPEDS_EF]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[L56_DOD_IPEDS_EF](
	[COLLEGE_ID] [varchar](3) NULL,
	[STUDENT_ID] [varchar](9) NOT NULL,
	[EDUCATION] [varchar](5) NULL,
	[Enrollment] [varchar](1) NULL,
	[DEGREE_FLAG] [varchar](1) NULL,
	[UNITS_ATTEMPTED] [decimal](6, 2) NULL,
	[YEAR] [varchar](4) NOT NULL,
	[LATTER_YEAR] [varchar](4) NOT NULL,
 CONSTRAINT [PK_DOD_IPEDS_LATTER_YEAR_YEAR_STUDENT_ID] PRIMARY KEY CLUSTERED 
(
	[LATTER_YEAR] DESC,
	[YEAR] DESC,
	[STUDENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
