DROP TABLE [dbo].[L56_DOD_IPEDS_RACE_CODES]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[L56_DOD_IPEDS_RACE_CODES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[L56_DOD_IPEDS_RACE_CODES](
	[RACE] [varchar](1) NOT NULL,
	[DESCRIPTION] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DOD_IPEDS_RACE] PRIMARY KEY CLUSTERED 
(
	[RACE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
