DROP TABLE [dbo].[L56_DOD_IPEDS_ENR_12]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[L56_DOD_IPEDS_ENR_12]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[L56_DOD_IPEDS_ENR_12](
	[COLLEGE_ID] [varchar](3) NULL,
	[STUDENT_ID] [varchar](9) NOT NULL,
	[ENROLLMENT] [varchar](1) NULL,
	[RACE] [varchar](7) NULL,
	[GENDER] [varchar](1) NULL,
	[RESIDENCY] [varchar](2) NULL,
	[DEGREE_FLAG] [varchar](1) NULL,
	[UNITS_ATTEMPTED] [decimal](8, 2) NULL,
	[YEAR] [varchar](4) NOT NULL,
	[LATER_YEAR] [varchar](4) NOT NULL,
 CONSTRAINT [PK_DOD_IPEDS_ENR_12_LATER_YEAR_YEAR_STUDENT_ID] PRIMARY KEY CLUSTERED 
(
	[LATER_YEAR] DESC,
	[YEAR] DESC,
	[STUDENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
