DROP TABLE [dbo].[CAST_SX_RPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAST_SX_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAST_SX_RPT](
	[CAST_SX_RPT_ID] [int] NOT NULL,
	[CAST_SX_RPT_FLAG] [bit] NOT NULL,
	[CAST_SX_WORK_ID] [varchar](10) NULL,
	[CASTSX_STUDENT_ID] [varchar](10) NULL,
	[CASTSX_COURSE_SECTION_ID] [varchar](19) NULL,
	[CASTSX_GI01] [varchar](3) NULL,
	[CASTSX_GI03] [varchar](3) NULL,
	[CASTSX_SB00] [varchar](9) NULL,
	[CASTSX_SB02] [varchar](3) NULL,
	[CASTSX_CB01] [varchar](12) NULL,
	[CASTSX_XB00] [varchar](6) NULL,
	[CASTSX_SX01] [varchar](6) NULL,
	[CASTSX_SX02] [varchar](6) NULL,
	[CASTSX_SX03] [varchar](4) NULL,
	[CASTSX_SX04] [varchar](3) NULL,
	[CASTSX_SX05] [varchar](5) NULL,
	[CASTSX_KEY_IDX] [varchar](38) NULL,
	[CASTSX_STU_GI03_IDX] [varchar](20) NULL,
	[CASTSX_CB00] [varchar](12) NULL,
	[CASTSX_SX06] [varchar](1) NULL,
	[CASTSX_ACAD_CREDENTIALS_ID] [varchar](10) NULL,
 CONSTRAINT [PK_SX_RPT_ID] PRIMARY KEY CLUSTERED 
(
	[CAST_SX_RPT_ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAST_SX_R__CAST___3A089B75]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAST_SX_RPT] ADD  DEFAULT ((1)) FOR [CAST_SX_RPT_FLAG]
END
GO
