DROP TABLE [dbo].[L56_DOD_IPEDS_HR]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[L56_DOD_IPEDS_HR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[L56_DOD_IPEDS_HR](
	[COLLEGE_ID] [varchar](3) NULL,
	[EMPLOYEE_ID] [varchar](9) NOT NULL,
	[SOC2010] [varchar](6) NULL,
	[IPEDS_CATEGORIES] [varchar](100) NULL,
	[SURVEY_YEAR] [varchar](10) NOT NULL,
 CONSTRAINT [PK_DOD_IPEDS_HR_EMPLOYEE_ID_SURVEY_YEAR] PRIMARY KEY CLUSTERED 
(
	[SURVEY_YEAR] DESC,
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
