DROP TABLE [dbo].[L56_COCI_PROGRAMS]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[L56_COCI_PROGRAMS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[L56_COCI_PROGRAMS](
	[COLLEGE] [varchar](50) NULL,
	[CONTROL_NUMBER] [int] NOT NULL,
	[TITLE] [varchar](150) NULL,
	[TOP_CODE] [varchar](100) NULL,
	[CIP_CODE] [varchar](100) NULL,
	[GOAL] [varchar](150) NULL,
	[AWARD] [varchar](150) NULL,
	[SUB_AWARD] [varchar](50) NULL,
	[APPROVED_DATE] [varchar](10) NULL,
	[CERT_UNITS] [varchar](30) NULL,
	[MAJOR_UNITS] [varchar](30) NULL,
	[STATUS] [varchar](30) NULL,
 CONSTRAINT [PK_COCI_PROGRAMS_CONTROL_NUMBER] PRIMARY KEY CLUSTERED 
(
	[CONTROL_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
