DROP TABLE [dbo].[CAST_SD_RPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAST_SD_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAST_SD_RPT](
	[CAST_SD_RPT_ID] [int] NOT NULL,
	[CAST_SD_RPT_FLAG] [bit] NOT NULL,
	[CAST_SD_WORK_ID] [varchar](10) NULL,
	[CASTSD_GI01] [varchar](3) NULL,
	[CASTSD_GI03] [varchar](3) NULL,
	[CASTSD_SB02] [varchar](3) NULL,
	[CASTSD_SB00] [varchar](9) NULL,
	[CASTSD_SD01] [varchar](1) NULL,
	[CASTSD_SD02] [varchar](3) NULL,
	[CASTSD_SD03] [varchar](1) NULL,
	[CASTSD_SD04] [varchar](3) NULL,
	[CASTSD_SD05] [varchar](1) NULL,
	[CASTSD_PERSON_ID] [varchar](10) NULL,
	[CASTSD_KEY_IDX] [varchar](20) NULL,
	[CAST_SD_WORK_ADDOPR] [varchar](20) NULL,
	[CAST_SD_WORK_ADDDATE] [datetime] NULL,
	[CAST_SD_WORK_CHGOPR] [varchar](20) NULL,
	[CAST_SD_WORK_CHGDATE] [datetime] NULL,
	[CASTSD_SD02_OVERRIDE] [varchar](1) NULL,
	[CASTSD_SD04_OVERRIDE] [varchar](1) NULL,
	[CASTSD_INSTITUTION_ID] [varchar](10) NULL,
	[CASTSD_MANUAL_UPDATE] [varchar](1) NULL,
 CONSTRAINT [PK_SD_RPT_ID] PRIMARY KEY CLUSTERED 
(
	[CAST_SD_RPT_ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAST_SD_R__CAST___02FF51F2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAST_SD_RPT] ADD  DEFAULT ((1)) FOR [CAST_SD_RPT_FLAG]
END
GO
