DROP TABLE [dbo].[CAST_XE_RPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAST_XE_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAST_XE_RPT](
	[CAST_XE_RPT_ID] [int] NOT NULL,
	[CAST_XE_RPT_FLAG] [bit] NOT NULL,
	[CAST_XE_WORK_ID] [varchar](10) NULL,
	[CASTXE_FACULTY_ID] [varchar](10) NULL,
	[CASTXE_COURSE_DEPT_NO] [varchar](12) NULL,
	[CASTXE_SECTION_IDENTIFIER] [varchar](6) NULL,
	[CASTXE_SESSION_IDENTIFIER] [varchar](2) NULL,
	[CASTXE_FAC_ASGMT_TYPE] [varchar](1) NULL,
	[CASTXE_FAC_ASGMT_PCT] [varchar](3) NULL,
	[CASTXE_FAC_ASGMT_FTE] [varchar](5) NULL,
	[CASTXE_COURSE_SECTION] [varchar](19) NULL,
	[CASTXE_FAC_ASGMT_PAY_RATE] [varchar](5) NULL,
	[CASTXE_GI03] [varchar](3) NULL,
	[CASTXE_GI01] [varchar](3) NULL,
	[CASTXE_EB00] [varchar](9) NULL,
	[CASTXE_CB00] [varchar](12) NULL,
	[CASTXE_COURSE_SEC_FAC_IDX] [varchar](32) NULL,
	[CASTXE_COURSE_SEC_FACULTY_ID] [varchar](10) NULL,
 CONSTRAINT [PK_XE_RPT_ID] PRIMARY KEY CLUSTERED 
(
	[CAST_XE_RPT_ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAST_XE_R__CAST___20D6A040]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAST_XE_RPT] ADD  DEFAULT ((1)) FOR [CAST_XE_RPT_FLAG]
END
GO
