DROP TABLE [dbo].[L56_DOD_COHORT_MAP]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[L56_DOD_COHORT_MAP]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[L56_DOD_COHORT_MAP](
	[REPORT] [varchar](15) NOT NULL,
	[YEAR] [varchar](4) NOT NULL,
	[GI03] [varchar](3) NOT NULL,
 CONSTRAINT [PK_DOD_IPEDS_REPORT_YEAR_GI03] PRIMARY KEY CLUSTERED 
(
	[REPORT] ASC,
	[YEAR] DESC,
	[GI03] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
