DROP TABLE [dbo].[L56_COCI_COURSES]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[L56_COCI_COURSES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[L56_COCI_COURSES](
	[COURSE_ID] [int] NULL,
	[COLLEGE] [varchar](50) NULL,
	[COLLEGE_TITLE_CB02] [varchar](150) NULL,
	[STATUS] [varchar](30) NULL,
	[CONTROL_NUMBER_CB00] [varchar](12) NOT NULL,
	[DEPARTMENT_NAME_CB01A] [varchar](50) NULL,
	[DEPARTMENT_NUMBER_CB01B] [varchar](12) NULL,
	[CREDIT_STATUS_CB04] [varchar](2) NULL,
	[MINIMUM_CONTACT_HOURS] [decimal](5, 2) NULL,
	[MAXIMUM_CONTACT_HOURS] [decimal](5, 2) NULL,
	[MINIMUM_UNITS_OF_CREDIT_CB07] [decimal](4, 2) NULL,
	[MAXIMUM_UNITS_OF_CREDIT_CB06] [decimal](4, 2) NULL,
	[COURSE_CLASSIFICATION_STATUS_CB11] [varchar](1) NULL,
	[EDUCATIONAL_ASSISTANCE_CLASS_INSTRUCTION_CB13] [varchar](1) NULL,
	[COURSE_PRIOR_TO_TRANSFER_LEVEL_CB21] [varchar](1) NULL,
	[FUNDING_AGENCY_CATEGORY_CB23] [varchar](1) NULL,
	[COURSE_BASIC_SKILLS_STATUS_CB08] [varchar](1) NULL,
	[STUDENT_ACCOUNTABILITY_MODEL_SAM_PRIORITY_CODE_CB09] [varchar](1) NULL,
	[COURSE_COOPERATIVE_WORK_EXPERIENCE_EDUCATION_STATUS_CB10] [varchar](1) NULL,
	[NONCREDIT_CATEGORY_CB22] [varchar](1) NULL,
	[TRANSFER_STATUS_CB05] [varchar](1) NULL,
	[COURSE_PROGRAM_STATUS_CB24] [varchar](1) NULL,
	[CCOURSE_GENERAL_EDUCATION_STATUS_CB25] [varchar](1) NULL,
	[SUPPORT_COURSE_STATUS_CB26] [varchar](1) NULL,
	[TOP_CODE_CB03] [varchar](150) NULL,
	[LAST_UPDATED_BY_COLLEGE] [varchar](10) NULL,
	[MINIMUM_OUTSIDE_OF_CLASS_HOURS] [decimal](5, 2) NULL,
	[MAXIMUM_OUTSIDE_OF_CLASS_HOURS] [decimal](5, 2) NULL,
	[MINIMUM_COURSE_CONTACT_HOURS] [decimal](5, 2) NULL,
	[MAXIMUM_COURSE_CONTACT_HOUR] [decimal](5, 2) NULL,
	[HOURS_OF_PAID_WORK] [decimal](5, 2) NULL,
	[HOURS_OF_UNPAID_WORK] [decimal](5, 2) NULL,
 CONSTRAINT [PK_COCI_COURSES_CB00] PRIMARY KEY CLUSTERED 
(
	[CONTROL_NUMBER_CB00] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
