DROP TABLE [dbo].[CAHR_EJ_RPT]
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAHR_EJ_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAHR_EJ_RPT](
	[CAHR_EJ_RPT_ID] [int] NOT NULL,
	[CAHR_EJ_RPT_FLAG] [bit] NOT NULL,
	[CAHR_EJWORK_ID] [varchar](10) NULL,
	[CAHREJW_EMPLOYEE] [varchar](10) NULL,
	[CAHREJW_GI01] [varchar](3) NULL,
	[CAHREJW_GI01_ORIG] [varchar](3) NULL,
	[CAHREJW_GI01_OVERRIDE_DATE] [datetime] NULL,
	[CAHREJW_GI01_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREJW_GI01_OVERRIDE_REASON] [text] NULL,
	[CAHREJW_EJ01] [varchar](10) NULL,
	[CAHREJW_EJ01_ORIG] [varchar](10) NULL,
	[CAHREJW_EJ01_OVERRIDE_DATE] [datetime] NULL,
	[CAHREJW_EJ01_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREJW_EJ01_OVERRIDE_REASON] [text] NULL,
	[CAHREJW_EJ02] [varchar](10) NULL,
	[CAHREJW_EJ02_ORIG] [varchar](10) NULL,
	[CAHREJW_EJ02_OVERRIDE_DATE] [datetime] NULL,
	[CAHREJW_EJ02_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREJW_EJ02_OVERRIDE_REASON] [text] NULL,
	[CAHREJW_EJ03] [varchar](10) NULL,
	[CAHREJW_EJ03_ORIG] [varchar](6) NULL,
	[CAHREJW_EJ03_OVERRIDE_DATE] [datetime] NULL,
	[CAHREJW_EJ03_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREJW_EJ03_OVERRIDE_REASON] [text] NULL,
	[CAHREJW_EJ04] [decimal](3, 1) NULL,
	[CAHREJW_EJ04_ORIG] [decimal](3, 1) NULL,
	[CAHREJW_EJ04_OVERRIDE_DATE] [datetime] NULL,
	[CAHREJW_EJ04_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREJW_EJ04_OVERRIDE_REASON] [text] NULL,
	[CAHREJW_EJ05] [decimal](5, 2) NULL,
	[CAHREJW_EJ05_ORIG] [decimal](5, 2) NULL,
	[CAHREJW_EJ05_OVERRIDE_DATE] [datetime] NULL,
	[CAHREJW_EJ05_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREJW_EJ05_OVERRIDE_REASON] [text] NULL,
	[CAHREJW_EJ08] [decimal](5, 2) NULL,
	[CAHREJW_EJ08_ORIG] [decimal](5, 2) NULL,
	[CAHREJW_EJ08_OVERRIDE_DATE] [datetime] NULL,
	[CAHREJW_EJ08_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREJW_EJ08_OVERRIDE_REASON] [varchar](1996) NULL,
	[CAHREJW_POSITION] [varchar](14) NULL,
	[CAHREJW_COURSE_SEC_FACULTY] [varchar](10) NULL,
	[CAHREJW_MANUAL_ADD_FLAG] [varchar](1) NULL,
	[CAHREJW_UNIQUE_KEY_IDX] [varchar](63) NULL,
	[CAHREJW_PAC_LDPD_ID] [varchar](10) NULL,
	[CAHREJW_CAMPUS_ORG_TYPE] [varchar](1) NULL,
	[CAHREJW_PLPA_ASGMT_ID] [varchar](10) NULL,
	[CAHREJW_CAMPUS_ORG_ID] [varchar](15) NULL,
	[CAHREJW_CAMPUS_ORG_ROLE] [varchar](5) NULL,
	[CAHREJW_PERPOS_ID] [varchar](10) NULL,
	[CAHREJW_PERPOSWG_ID] [varchar](10) NULL,
	[CAHREJW_EJ_SUMMARY_ID] [varchar](10) NULL,
	[CAHREJW_GI03] [varchar](3) NULL,
	[CAHREJW_HRP_ID] [varchar](10) NULL,
	[CAHR_EJWORK_ADDOPR] [varchar](20) NULL,
	[CAHR_EJWORK_ADDDATE] [datetime] NULL,
	[CAHR_EJWORK_CHGOPR] [varchar](20) NULL,
	[CAHR_EJWORK_CHGDATE] [datetime] NULL,
	[CAHREJW_USER1] [varchar](10) NULL,
	[CAHREJW_USER2] [varchar](10) NULL,
	[CAHREJW_USER3] [varchar](10) NULL,
	[CAHREJW_USER4] [varchar](10) NULL,
	[CAHREJW_USER5] [varchar](10) NULL,
	[CAHREJW_USER6] [varchar](10) NULL,
	[CAHREJW_USER7] [varchar](10) NULL,
	[CAHREJW_USER8] [varchar](10) NULL,
	[CAHREJW_USER9] [varchar](10) NULL,
	[CAHREJW_USER10] [varchar](10) NULL,
	[CAHREJW_SECTION_NO_WEEKS] [decimal](3, 0) NULL,
	[CAHREJW_SECTION_ID] [varchar](19) NULL,
	[CAHREJW_SECTION_PCT] [decimal](6, 2) NULL,
	[CAHREJW_SECTION_SYNONYM] [varchar](11) NULL,
	[CAHREJW_SECTION_CREDIT_TYPE] [varchar](5) NULL,
	[CAHREJW_SECTION_CLOCK_HOURS] [decimal](8, 2) NULL,
	[CAHREJW_SECTION_CONTACT_HRS] [decimal](6, 2) NULL,
	[CAHREJW_SECTION_TEACH_ARRGT] [varchar](10) NULL,
	[CAHREJW_ASGMT_INSTR_METHOD] [varchar](5) NULL,
	[CAHREJW_ASGMT_LOAD] [decimal](6, 2) NULL,
	[CAHREJW_ASGMT_LOCATION] [varchar](5) NULL,
	[CAHREJW_ASGMT_CON_MEASURE] [varchar](10) NULL,
	[CARHEJW_ASGMT_CONTRACT_TYPE] [varchar](30) NULL,
	[CAHREJW_ASGMT_PAC_LP_POS_ID] [varchar](10) NULL,
	[CAHREJW_ORG_ENTRY_ID] [varchar](10) NULL,
	[CAHREJW_POS_CLASSIFICATION] [varchar](30) NULL,
 CONSTRAINT [PK_EJ_RPT_ID] PRIMARY KEY CLUSTERED 
(
	[CAHR_EJ_RPT_ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAHR_EJ_R__CAHR___7C0F2BB6]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAHR_EJ_RPT] ADD  DEFAULT ((1)) FOR [CAHR_EJ_RPT_FLAG]
END
GO
