DROP TABLE [dbo].[CAHR_EB_RPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAHR_EB_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAHR_EB_RPT](
	[CAHR_EB_RPT_ID] [int] NOT NULL,
	[CAHR_EB_RPT_FLAG] [bit] NOT NULL,
	[CAHR_EB_WORK_ID] [varchar](10) NULL,
	[CAHREB_CALC_EB07] [varchar](25) NULL,
	[CAHREB_EB07] [varchar](25) NULL,
	[CAHREB_EB07_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_EB07_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_EB07_OVERRIDE_REASON] [text] NULL,
	[CAHREB_CALC_EB08] [varchar](25) NULL,
	[CAHREB_EB08] [varchar](25) NULL,
	[CAHREB_EB08_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_EB08_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_EB08_OVERRIDE_REASON] [text] NULL,
	[CAHREB_CALC_EB09] [varchar](25) NULL,
	[CAHREB_EB09] [varchar](25) NULL,
	[CAHREB_EB09_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_EB09_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_EB09_OVERRIDE_REASON] [text] NULL,
	[CAHREB_CALC_EB10] [varchar](8) NULL,
	[CAHREB_EB10] [varchar](8) NULL,
	[CAHREB_EB10_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_EB10_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_EB10_OVERRIDE_REASON] [text] NULL,
	[CAHREB_CALC_EB11] [varchar](25) NULL,
	[CAHREB_EB11] [varchar](25) NULL,
	[CAHREB_EB11_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_EB11_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_EB11_OVERRIDE_REASON] [text] NULL,
	[CAHREB_CALC_EB12] [decimal](7, 0) NULL,
	[CAHREB_EB12] [decimal](7, 0) NULL,
	[CAHREB_EB12_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_EB12_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_EB12_OVERRIDE_REASON] [varchar](1996) NULL,
	[CAHREB_CALC_EB13] [decimal](7, 0) NULL,
	[CAHREB_EB13] [decimal](7, 0) NULL,
	[CAHREB_EB13_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_EB13_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_EB13_OVERRIDE_REASON] [text] NULL,
	[CAHREB_INCLUDE_FLAG] [varchar](1) NULL,
	[CAHREB_INCL_OVERRIDE_DATE] [datetime] NULL,
	[CAHREB_INCL_OVERRIDE_OPR] [varchar](25) NULL,
	[CAHREB_INCL_OVERRIDE_REASON] [text] NULL,
	[CAHREB_MANUAL_ADD_FLAG] [varchar](1) NULL,
	[CAHREB_MANUAL_ADD_OVR_REASON] [text] NULL,
	[CAHR_EB_WORK_ADDDATE] [datetime] NULL,
	[CAHR_EB_WORK_ADDOPR] [varchar](20) NULL,
	[CAHR_EB_WORK_CHGDATE] [datetime] NULL,
	[CAHR_EB_WORK_CHGOPR] [varchar](20) NULL,
	[CAHREB_USER1] [varchar](10) NULL,
	[CAHREB_USER2] [varchar](10) NULL,
	[CAHREB_USER3] [varchar](10) NULL,
	[CAHREB_USER4] [varchar](10) NULL,
	[CAHREB_USER5] [varchar](10) NULL,
	[CAHREB_USER6] [varchar](10) NULL,
	[CAHREB_USER7] [varchar](10) NULL,
	[CAHREB_USER8] [varchar](10) NULL,
	[CAHREB_USER9] [varchar](10) NULL,
	[CAHREB_USER10] [varchar](10) NULL,
	[CAHREB_GI03] [varchar](3) NULL,
	[CAHREB_PERSON_ID] [varchar](10) NULL,
	[CAHREB_UNIQUE_KEY_IDX] [varchar](14) NULL,
	[CAHREB_EB14] [varchar](21) NULL,
	[CAHREB_EB00] [varchar](10) NULL,
	[CAHREB_EB01] [varchar](1) NULL,
	[CAHREB_EB02] [varchar](8) NULL,
	[CAHREB_EB03] [varchar](2) NULL,
	[CAHREB_EB04] [varchar](3) NULL,
	[CAHREB_EB05] [varchar](10) NULL,
	[CAHREB_EB06] [varchar](10) NULL,
	[CAHREB_GI01] [varchar](3) NULL,
 CONSTRAINT [PK_EB_RPT_ID] PRIMARY KEY CLUSTERED 
(
	[CAHR_EB_RPT_ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAHR_EB_R__CAHR___01D55838]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAHR_EB_RPT] ADD  DEFAULT ((1)) FOR [CAHR_EB_RPT_FLAG]
END
GO
