DROP TABLE [dbo].[CAST_SY_RPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAST_SY_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAST_SY_RPT](
	[CAST_SY_RPT_ID] [int] NOT NULL,
	[CAST_SY_RPT_FLAG] [bit] NOT NULL,
	[CAST_SY_WORK_ID] [varchar](10) NULL,
	[CASTSY_GI01] [varchar](3) NULL,
	[CASTSY_GI03] [varchar](3) NULL,
	[CASTSY_SB00] [varchar](10) NULL,
	[CASTSY_CB00] [varchar](12) NULL,
	[CASTSY_CB01] [varchar](12) NULL,
	[CASTSY_SY01] [datetime] NULL,
	[CASTSY_SY02] [varchar](1) NULL,
	[CASTSY_SY03] [varchar](10) NULL,
	[CASTSY_SY04] [varchar](3) NULL,
	[CASTSY_STUDENT_ID] [varchar](10) NULL,
	[CASTSY_COURSE_SECTION] [varchar](20) NULL,
	[CAST_SY_WORK_ADDOPR] [varchar](20) NULL,
	[CAST_SY_WORK_ADDDATE] [datetime] NULL,
	[CAST_SY_WORK_CHGOPR] [varchar](20) NULL,
	[CAST_SY_WORK_CHGDATE] [datetime] NULL,
	[CASTSY_KEY_IDX] [varchar](25) NULL,
	[CASTSY_STAC_ID] [varchar](10) NULL,
	[CASTSY_COURSE_ID] [varchar](10) NULL,
 CONSTRAINT [PK_SY_RPT_ID] PRIMARY KEY CLUSTERED 
(
	[CAST_SY_RPT_ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAST_SY_R__CAST___417185B7]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAST_SY_RPT] ADD  DEFAULT ((1)) FOR [CAST_SY_RPT_FLAG]
END
GO
