DROP TABLE [dbo].[CAST_CW_RPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CAST_CW_RPT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CAST_CW_RPT](
	[CAST_CW_RPT_ID] [bigint] NOT NULL,
	[CAST_CW_RPT_FLAG] [bit] NOT NULL,
	[CAST_CALWORK_CW_WORK_ID] [varchar](10) NULL,
	[CASTCW_STUDENT_ID] [varchar](10) NULL,
	[CASTCW_GI01] [varchar](3) NULL,
	[CASTCW_SC12] [varchar](1) NULL,
	[CASTCW_SC13] [varchar](6) NULL,
	[CASTCW_SC14] [varchar](8) NULL,
	[CASTCW_SC15] [varchar](8) NULL,
	[CASTCW_SC16] [varchar](2) NULL,
	[CASTCW_SC17] [varchar](4) NULL,
	[CASTCW_PERPOS_ID] [varchar](10) NULL,
	[CASTCW_STCWP_ID] [varchar](30) NULL,
	[CASTCW_KEY_IDX] [varchar](45) NULL,
	[CASTCW_GI03] [varchar](3) NULL,
	[CASTCW_INSTITUTION_ID] [varchar](10) NULL,
	[CASTCW_MANUAL_FLAG] [varchar](1) NULL,
	[CASTCW_SB00] [varchar](9) NULL,
	[CAST_CALWORK_CW_WORK_ADDOPR] [varchar](20) NULL,
	[CAST_CALWORK_CW_WORK_ADDDATE] [datetime] NULL,
	[CAST_CALWORK_CW_WORK_CHGOPR] [varchar](20) NULL,
	[CAST_CALWORK_CW_WORK_CHGDATE] [datetime] NULL
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CAST_CW_R__CAST___5A1B1013]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CAST_CW_RPT] ADD  DEFAULT ((1)) FOR [CAST_CW_RPT_FLAG]
END
GO
